### ISSUE TITLE
Looking good so far - further updates?

### ISSUE THREAD

**Issue by cscd98** [m2-boilerplate/theme-frontend-bootstrap#1]
Hi @thampe,

How complete is the development of this? v4.0.0-beta.2 is the latest Bootstrap release and I'm tempted to use this theme for another project, but I wanted to sure it is updated and you are still working on it?

Also the composer.json needs updating for PHP 7.1

"php": "7.0.2|7.0.4|~7.0.6|~7.1.0"

And Magento 2.2

101.0.*

Many thanks.

**Comment by cscd98** [comment]
@thampe 

https://github.com/m2-boilerplate/theme-frontend-bootstrap/pull/2

Develop branch will need merging with master as well

**Comment by thampe** [comment]
Hi,

right now I have no time to work on this, but I have merged your pull request.

Sorry. 

-Thomas
